/* The following code was generated by JFlex 1.4.3 on 20/04/20 23:31 */

package src;
import static src.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 20/04/20 23:31 from the specification file
 * <tt>C:/Users/9/OneDrive/Documentos/NetBeansProjects/vmc/src/src/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\46\2\0\1\0\22\0\1\47\1\64\1\3\2\0"+
    "\1\67\1\62\1\0\1\54\1\55\1\53\1\51\1\0\1\52\1\0"+
    "\1\45\12\2\1\0\1\70\1\66\1\50\1\65\2\0\2\1\1\26"+
    "\1\31\1\25\1\30\1\1\1\34\1\4\2\1\1\27\1\36\2\1"+
    "\1\37\1\1\1\43\1\32\2\1\1\40\4\1\1\60\1\0\1\61"+
    "\1\0\1\1\1\0\1\15\1\7\1\13\1\23\1\11\1\22\1\21"+
    "\1\14\1\12\1\1\1\42\1\17\1\44\1\5\1\20\1\41\1\1"+
    "\1\16\1\33\1\6\1\24\1\1\1\35\1\1\1\10\1\1\1\56"+
    "\1\63\1\57\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\30\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\3\22\2\23\1\1\1\24\7\2"+
    "\1\25\11\2\1\26\12\2\1\27\13\2\1\7\1\30"+
    "\1\7\1\31\1\32\1\0\1\22\1\23\1\33\15\2"+
    "\1\34\30\2\1\0\1\35\1\2\1\36\26\2\1\37"+
    "\2\2\1\40\2\2\1\41\1\3\1\42\2\2\1\43"+
    "\1\2\1\44\6\2\1\45\5\2\1\46\1\47\2\2"+
    "\1\50\10\2\1\51\4\2\1\52\1\53\3\2\1\54"+
    "\1\55\1\7\1\56\1\57\10\2\1\60\1\61\2\2"+
    "\1\62\1\63\2\2\1\64\2\2\1\65\3\2\1\66"+
    "\1\67\2\2\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[244];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\71\0\344\0\u011d\0\u0156"+
    "\0\u018f\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5\0\u031e"+
    "\0\u0357\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6"+
    "\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c\0\71\0\u0675"+
    "\0\u06ae\0\u06e7\0\u0720\0\u0759\0\u0792\0\71\0\71\0\71"+
    "\0\71\0\71\0\u07cb\0\u0804\0\u083d\0\u0876\0\u08af\0\u0759"+
    "\0\71\0\u08e8\0\u0921\0\u095a\0\u0993\0\u09cc\0\u0a05\0\u0a3e"+
    "\0\162\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd"+
    "\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c\0\u0d95"+
    "\0\u0dce\0\u0e07\0\u0e40\0\u0e79\0\u0eb2\0\162\0\u0eeb\0\u0f24"+
    "\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\u1041\0\u107a\0\u10b3\0\u10ec"+
    "\0\u1125\0\u115e\0\71\0\71\0\71\0\71\0\u1197\0\71"+
    "\0\71\0\162\0\u11d0\0\u1209\0\u1242\0\u127b\0\u12b4\0\u12ed"+
    "\0\u1326\0\u135f\0\u1398\0\u13d1\0\u140a\0\u1443\0\u147c\0\162"+
    "\0\u14b5\0\u14ee\0\u1527\0\u1560\0\u1599\0\u15d2\0\u160b\0\u1644"+
    "\0\u167d\0\u16b6\0\u16ef\0\u1728\0\u1761\0\u179a\0\u17d3\0\u180c"+
    "\0\u1845\0\u187e\0\u18b7\0\u18f0\0\u1929\0\u1962\0\u199b\0\u19d4"+
    "\0\u1a0d\0\162\0\u1a46\0\162\0\u1a7f\0\u1ab8\0\u1af1\0\u1b2a"+
    "\0\u1b63\0\u1b9c\0\u1bd5\0\u1c0e\0\u1c47\0\u1c80\0\u1cb9\0\u1cf2"+
    "\0\u1d2b\0\u1d64\0\u1d9d\0\u1dd6\0\u1e0f\0\u1e48\0\u1e81\0\u1eba"+
    "\0\u1ef3\0\u1f2c\0\162\0\u1f65\0\u1f9e\0\162\0\u1fd7\0\u2010"+
    "\0\162\0\71\0\162\0\u2049\0\u2082\0\162\0\u20bb\0\162"+
    "\0\u20f4\0\u212d\0\u2166\0\u219f\0\u21d8\0\u2211\0\162\0\u224a"+
    "\0\u2283\0\u22bc\0\u22f5\0\u232e\0\162\0\162\0\u2367\0\u23a0"+
    "\0\162\0\u23d9\0\u2412\0\u244b\0\u2484\0\u24bd\0\u24f6\0\u252f"+
    "\0\u2568\0\162\0\u25a1\0\u25da\0\u2613\0\u264c\0\162\0\162"+
    "\0\u2685\0\u26be\0\u26f7\0\162\0\162\0\162\0\162\0\162"+
    "\0\u2730\0\u2769\0\u27a2\0\u27db\0\u2814\0\u284d\0\u2886\0\u28bf"+
    "\0\162\0\162\0\u28f8\0\u2931\0\162\0\162\0\u296a\0\u29a3"+
    "\0\162\0\u29dc\0\u2a15\0\162\0\u2a4e\0\u2a87\0\u2ac0\0\162"+
    "\0\162\0\u2af9\0\u2b32\0\162";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[244];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\3\1\7\1\10"+
    "\1\3\1\11\1\12\1\13\3\3\1\14\2\3\1\15"+
    "\1\16\1\3\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\3"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\72\0\2\3"+
    "\1\0\41\3\26\0\1\4\67\0\2\3\1\0\1\3"+
    "\1\62\37\3\25\0\2\3\1\0\12\3\1\63\26\3"+
    "\25\0\2\3\1\0\4\3\1\64\5\3\1\65\26\3"+
    "\25\0\2\3\1\0\13\3\1\66\13\3\1\67\11\3"+
    "\25\0\2\3\1\0\1\3\1\70\14\3\1\71\22\3"+
    "\25\0\2\3\1\0\10\3\1\72\2\3\1\73\1\74"+
    "\24\3\25\0\2\3\1\0\14\3\1\75\24\3\25\0"+
    "\2\3\1\0\6\3\1\76\2\3\1\77\1\3\1\100"+
    "\1\101\24\3\25\0\2\3\1\0\5\3\1\102\6\3"+
    "\1\103\24\3\25\0\2\3\1\0\1\3\1\104\25\3"+
    "\1\105\11\3\25\0\2\3\1\0\11\3\1\106\1\3"+
    "\1\107\1\110\24\3\25\0\2\3\1\0\11\3\1\111"+
    "\27\3\25\0\2\3\1\0\6\3\1\112\4\3\1\113"+
    "\25\3\25\0\2\3\1\0\14\3\1\114\24\3\25\0"+
    "\2\3\1\0\2\3\1\115\3\3\1\116\32\3\25\0"+
    "\2\3\1\0\6\3\1\117\32\3\25\0\2\3\1\0"+
    "\11\3\1\120\27\3\25\0\2\3\1\0\10\3\1\121"+
    "\30\3\25\0\2\3\1\0\6\3\1\122\32\3\25\0"+
    "\2\3\1\0\11\3\1\123\6\3\1\124\20\3\25\0"+
    "\2\3\1\0\11\3\1\125\2\3\1\126\24\3\25\0"+
    "\2\3\1\0\20\3\1\127\20\3\25\0\2\3\1\0"+
    "\14\3\1\130\24\3\25\0\2\3\1\0\11\3\1\131"+
    "\27\3\71\0\1\132\2\0\1\133\67\0\1\134\71\0"+
    "\1\135\70\0\1\133\1\136\67\0\1\133\1\0\1\136"+
    "\66\0\1\133\72\0\1\137\100\0\1\140\71\0\1\140"+
    "\55\0\1\141\70\0\1\141\14\0\1\141\53\0\1\141"+
    "\15\0\1\141\3\0\2\3\1\0\2\3\1\142\36\3"+
    "\25\0\2\3\1\0\20\3\1\143\20\3\25\0\2\3"+
    "\1\0\2\3\1\144\36\3\25\0\2\3\1\0\5\3"+
    "\1\145\33\3\25\0\2\3\1\0\27\3\1\146\11\3"+
    "\25\0\2\3\1\0\35\3\1\147\3\3\25\0\2\3"+
    "\1\0\2\3\1\142\4\3\1\150\31\3\25\0\2\3"+
    "\1\0\11\3\1\151\27\3\25\0\2\3\1\0\11\3"+
    "\1\152\27\3\25\0\2\3\1\0\1\3\1\153\37\3"+
    "\25\0\2\3\1\0\1\3\1\154\37\3\25\0\2\3"+
    "\1\0\1\3\1\155\37\3\25\0\2\3\1\0\13\3"+
    "\1\156\25\3\25\0\2\3\1\0\14\3\1\157\24\3"+
    "\25\0\2\3\1\0\12\3\1\160\26\3\25\0\2\3"+
    "\1\0\13\3\1\161\2\3\1\162\22\3\25\0\2\3"+
    "\1\0\20\3\1\114\20\3\25\0\2\3\1\0\2\3"+
    "\1\163\36\3\25\0\2\3\1\0\2\3\1\164\36\3"+
    "\25\0\2\3\1\0\12\3\1\165\26\3\25\0\2\3"+
    "\1\0\11\3\1\166\27\3\25\0\2\3\1\0\1\3"+
    "\1\167\37\3\25\0\2\3\1\0\12\3\1\170\26\3"+
    "\25\0\2\3\1\0\1\3\1\171\37\3\25\0\2\3"+
    "\1\0\14\3\1\172\24\3\25\0\2\3\1\0\3\3"+
    "\1\173\35\3\25\0\2\3\1\0\11\3\1\174\1\175"+
    "\26\3\25\0\2\3\1\0\25\3\1\176\13\3\25\0"+
    "\2\3\1\0\7\3\1\177\31\3\25\0\2\3\1\0"+
    "\6\3\1\200\32\3\25\0\2\3\1\0\5\3\1\201"+
    "\33\3\25\0\2\3\1\0\12\3\1\202\26\3\25\0"+
    "\2\3\1\0\3\3\1\203\35\3\25\0\2\3\1\0"+
    "\7\3\1\204\31\3\25\0\2\3\1\0\6\3\1\205"+
    "\32\3\25\0\2\3\1\0\3\3\1\206\35\3\25\0"+
    "\2\3\1\0\40\3\1\207\25\0\2\3\1\0\6\3"+
    "\1\210\32\3\24\0\46\132\1\0\22\132\2\0\1\211"+
    "\67\0\2\3\1\0\5\3\1\212\33\3\25\0\2\3"+
    "\1\0\5\3\1\142\33\3\25\0\2\3\1\0\11\3"+
    "\1\213\27\3\25\0\2\3\1\0\5\3\1\214\33\3"+
    "\25\0\2\3\1\0\11\3\1\215\27\3\25\0\2\3"+
    "\1\0\13\3\1\216\25\3\25\0\2\3\1\0\12\3"+
    "\1\142\26\3\25\0\2\3\1\0\27\3\1\217\11\3"+
    "\25\0\2\3\1\0\2\3\1\220\36\3\25\0\2\3"+
    "\1\0\15\3\1\142\23\3\25\0\2\3\1\0\11\3"+
    "\1\221\13\3\1\222\13\3\25\0\2\3\1\0\27\3"+
    "\1\143\11\3\25\0\2\3\1\0\11\3\1\62\27\3"+
    "\25\0\2\3\1\0\14\3\1\223\24\3\25\0\2\3"+
    "\1\0\6\3\1\224\32\3\25\0\2\3\1\0\5\3"+
    "\1\225\6\3\1\226\24\3\25\0\2\3\1\0\11\3"+
    "\1\227\27\3\25\0\2\3\1\0\11\3\1\230\27\3"+
    "\25\0\2\3\1\0\27\3\1\231\11\3\25\0\2\3"+
    "\1\0\2\3\1\232\36\3\25\0\2\3\1\0\15\3"+
    "\1\233\23\3\25\0\2\3\1\0\11\3\1\221\27\3"+
    "\25\0\2\3\1\0\2\3\1\234\36\3\25\0\2\3"+
    "\1\0\13\3\1\144\25\3\25\0\2\3\1\0\2\3"+
    "\1\235\36\3\25\0\2\3\1\0\6\3\1\236\32\3"+
    "\25\0\2\3\1\0\5\3\1\237\33\3\25\0\2\3"+
    "\1\0\5\3\1\240\33\3\25\0\2\3\1\0\13\3"+
    "\1\241\25\3\25\0\2\3\1\0\1\3\1\242\37\3"+
    "\25\0\2\3\1\0\11\3\1\243\27\3\25\0\2\3"+
    "\1\0\13\3\1\244\25\3\25\0\2\3\1\0\6\3"+
    "\1\245\32\3\25\0\2\3\1\0\17\3\1\246\21\3"+
    "\25\0\2\3\1\0\13\3\1\247\25\3\25\0\2\3"+
    "\1\0\35\3\1\250\3\3\25\0\2\3\1\0\1\3"+
    "\1\251\37\3\26\0\1\211\52\0\1\252\14\0\2\3"+
    "\1\0\36\3\1\253\2\3\25\0\2\3\1\0\7\3"+
    "\1\254\31\3\25\0\2\3\1\0\20\3\1\255\20\3"+
    "\25\0\2\3\1\0\27\3\1\256\11\3\25\0\2\3"+
    "\1\0\6\3\1\257\32\3\25\0\2\3\1\0\13\3"+
    "\1\260\25\3\25\0\2\3\1\0\5\3\1\261\33\3"+
    "\25\0\2\3\1\0\7\3\1\262\31\3\25\0\2\3"+
    "\1\0\1\3\1\263\37\3\25\0\2\3\1\0\12\3"+
    "\1\233\26\3\25\0\2\3\1\0\1\3\1\264\37\3"+
    "\25\0\2\3\1\0\2\3\1\265\36\3\25\0\2\3"+
    "\1\0\7\3\1\266\31\3\25\0\2\3\1\0\5\3"+
    "\1\267\33\3\25\0\2\3\1\0\6\3\1\270\32\3"+
    "\25\0\2\3\1\0\14\3\1\142\24\3\25\0\2\3"+
    "\1\0\11\3\1\271\27\3\25\0\2\3\1\0\6\3"+
    "\1\272\32\3\25\0\2\3\1\0\1\3\1\273\37\3"+
    "\25\0\2\3\1\0\16\3\1\274\22\3\25\0\2\3"+
    "\1\0\12\3\1\275\26\3\25\0\2\3\1\0\5\3"+
    "\1\276\33\3\25\0\2\3\1\0\2\3\1\277\36\3"+
    "\25\0\2\3\1\0\6\3\1\300\32\3\25\0\2\3"+
    "\1\0\14\3\1\301\24\3\25\0\2\3\1\0\6\3"+
    "\1\302\32\3\25\0\2\3\1\0\5\3\1\303\33\3"+
    "\25\0\2\3\1\0\6\3\1\304\32\3\25\0\2\3"+
    "\1\0\4\3\1\305\12\3\1\306\21\3\25\0\2\3"+
    "\1\0\1\3\1\307\37\3\25\0\2\3\1\0\16\3"+
    "\1\310\22\3\25\0\2\3\1\0\14\3\1\311\24\3"+
    "\25\0\2\3\1\0\5\3\1\312\33\3\25\0\2\3"+
    "\1\0\7\3\1\313\31\3\25\0\2\3\1\0\6\3"+
    "\1\314\32\3\25\0\2\3\1\0\2\3\1\315\36\3"+
    "\25\0\2\3\1\0\1\3\1\316\37\3\25\0\2\3"+
    "\1\0\1\3\1\64\37\3\25\0\2\3\1\0\7\3"+
    "\1\317\31\3\25\0\2\3\1\0\15\3\1\320\23\3"+
    "\25\0\2\3\1\0\6\3\1\321\32\3\25\0\2\3"+
    "\1\0\12\3\1\322\26\3\25\0\2\3\1\0\7\3"+
    "\1\323\31\3\25\0\2\3\1\0\7\3\1\324\31\3"+
    "\25\0\2\3\1\0\12\3\1\325\26\3\25\0\2\3"+
    "\1\0\14\3\1\326\24\3\25\0\2\3\1\0\5\3"+
    "\1\327\33\3\25\0\2\3\1\0\5\3\1\330\33\3"+
    "\25\0\2\3\1\0\20\3\1\331\20\3\25\0\2\3"+
    "\1\0\6\3\1\332\32\3\25\0\2\3\1\0\1\3"+
    "\1\333\37\3\25\0\2\3\1\0\5\3\1\334\33\3"+
    "\25\0\2\3\1\0\7\3\1\335\31\3\25\0\2\3"+
    "\1\0\5\3\1\151\33\3\25\0\2\3\1\0\20\3"+
    "\1\336\20\3\25\0\2\3\1\0\1\3\1\337\37\3"+
    "\25\0\2\3\1\0\11\3\1\340\27\3\25\0\2\3"+
    "\1\0\14\3\1\341\24\3\25\0\2\3\1\0\5\3"+
    "\1\342\33\3\25\0\2\3\1\0\1\3\1\343\37\3"+
    "\25\0\2\3\1\0\2\3\1\344\36\3\25\0\2\3"+
    "\1\0\27\3\1\345\11\3\25\0\2\3\1\0\14\3"+
    "\1\346\24\3\25\0\2\3\1\0\11\3\1\347\27\3"+
    "\25\0\2\3\1\0\6\3\1\350\32\3\25\0\2\3"+
    "\1\0\27\3\1\351\11\3\25\0\2\3\1\0\6\3"+
    "\1\352\32\3\25\0\2\3\1\0\12\3\1\353\26\3"+
    "\25\0\2\3\1\0\12\3\1\354\26\3\25\0\2\3"+
    "\1\0\17\3\1\355\21\3\25\0\2\3\1\0\17\3"+
    "\1\356\21\3\25\0\2\3\1\0\11\3\1\357\27\3"+
    "\25\0\2\3\1\0\14\3\1\360\24\3\25\0\2\3"+
    "\1\0\14\3\1\361\24\3\25\0\2\3\1\0\12\3"+
    "\1\362\26\3\25\0\2\3\1\0\6\3\1\363\32\3"+
    "\25\0\2\3\1\0\14\3\1\364\24\3\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11115];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\31\1\1\11\6\1\5\11"+
    "\6\1\1\11\51\1\4\11\1\0\2\11\47\1\1\0"+
    "\40\1\1\11\112\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[244];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 166) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 31: 
          { lexeme=yytext(); return Para;
          }
        case 57: break;
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 58: break;
        case 8: 
          { lexeme = yytext(); return Igual;
          }
        case 59: break;
        case 44: 
          { lexeme = yytext(); return Public;
          }
        case 60: break;
        case 16: 
          { lexeme = yytext(); return CorcheteIzq;
          }
        case 61: break;
        case 36: 
          { lexeme = yytext(); return Final;
          }
        case 62: break;
        case 40: 
          { lexeme = yytext(); return Vacio;
          }
        case 63: break;
        case 52: 
          { lexeme=yytext(); return Mientras;
          }
        case 64: break;
        case 42: 
          { lexeme = yytext(); return Static;
          }
        case 65: break;
        case 17: 
          { lexeme = yytext(); return CorcheteDer;
          }
        case 66: break;
        case 30: 
          { lexeme=yytext(); return Else;
          }
        case 67: break;
        case 45: 
          { lexeme = yytext(); return Romper;
          }
        case 68: break;
        case 34: 
          { lexeme = yytext(); return Break;
          }
        case 69: break;
        case 38: 
          { lexeme=yytext(); return Hacer;
          }
        case 70: break;
        case 41: 
          { lexeme = yytext(); return Define;
          }
        case 71: break;
        case 28: 
          { lexeme=yytext(); return For;
          }
        case 72: break;
        case 6: 
          { lexeme = yytext(); return Linea;
          }
        case 73: break;
        case 9: 
          { lexeme = yytext(); return Suma;
          }
        case 74: break;
        case 19: 
          { lexeme = yytext(); return Op_relacional;
          }
        case 75: break;
        case 18: 
          { lexeme=yytext(); return Op_logico;
          }
        case 76: break;
        case 46: 
          { lexeme = yytext(); return Incluye;
          }
        case 77: break;
        case 25: 
          { lexeme = yytext();return Asignacion;
          }
        case 78: break;
        case 24: 
          { lexeme = yytext(); return Op_atribucion;
          }
        case 79: break;
        case 26: 
          { lexeme = yytext(); return Op_incremento;
          }
        case 80: break;
        case 3: 
          { lexeme=yytext(); return Numero;
          }
        case 81: break;
        case 49: 
          { lexeme = yytext(); return Continue;
          }
        case 82: break;
        case 12: 
          { lexeme = yytext(); return ParIzq;
          }
        case 83: break;
        case 14: 
          { lexeme = yytext(); return LlaveIzq;
          }
        case 84: break;
        case 4: 
          { lexeme=yytext(); return Comillas;
          }
        case 85: break;
        case 13: 
          { lexeme = yytext(); return ParDer;
          }
        case 86: break;
        case 32: 
          { lexeme = yytext(); return Void;
          }
        case 87: break;
        case 15: 
          { lexeme = yytext(); return LlaveDer;
          }
        case 88: break;
        case 43: 
          { lexeme=yytext(); return Cadena;
          }
        case 89: break;
        case 37: 
          { lexeme = yytext(); return Clase;
          }
        case 90: break;
        case 51: 
          { lexeme = yytext(); return Estatico;
          }
        case 91: break;
        case 22: 
          { lexeme=yytext(); return Do;
          }
        case 92: break;
        case 50: 
          { lexeme=yytext(); return Entonces;
          }
        case 93: break;
        case 5: 
          { lexeme = yytext(); return Division;
          }
        case 94: break;
        case 56: 
          { lexeme = yytext(); return Sino;
          }
        case 95: break;
        case 48: 
          { lexeme = yytext(); return Publico;
          }
        case 96: break;
        case 53: 
          { lexeme = yytext(); return Continuar;
          }
        case 97: break;
        case 47: 
          { lexeme = yytext(); return Include;
          }
        case 98: break;
        case 10: 
          { lexeme = yytext(); return Resta;
          }
        case 99: break;
        case 23: 
          { lexeme=yytext(); return Si;
          }
        case 100: break;
        case 1: 
          { return ERROR;
          }
        case 101: break;
        case 20: 
          { lexeme = yytext(); return P_coma;
          }
        case 102: break;
        case 27: 
          { lexeme=yytext(); return Tipo;
          }
        case 103: break;
        case 11: 
          { lexeme = yytext(); return Multiplicacion;
          }
        case 104: break;
        case 39: 
          { lexeme=yytext(); return While;
          }
        case 105: break;
        case 7: 
          { /*Ignore*/
          }
        case 106: break;
        case 29: 
          { lexeme = yytext(); return Op_booleano;
          }
        case 107: break;
        case 21: 
          { lexeme=yytext(); return If;
          }
        case 108: break;
        case 55: 
          { lexeme = yytext(); return FinDefinido;
          }
        case 109: break;
        case 33: 
          { lexeme = yytext(); return Main;
          }
        case 110: break;
        case 35: 
          { lexeme = yytext(); return Class;
          }
        case 111: break;
        case 54: 
          { lexeme = yytext(); return SiDefinido;
          }
        case 112: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
