
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 20 23:31:50 CDT 2020
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 14;
  public static final int Estatico = 29;
  public static final int Class = 51;
  public static final int Entero = 33;
  public static final int Op_booleano = 17;
  public static final int ParIzq = 26;
  public static final int If = 4;
  public static final int Void = 30;
  public static final int Clase = 38;
  public static final int Static = 28;
  public static final int Else = 6;
  public static final int Break = 52;
  public static final int CorcheteIzq = 25;
  public static final int Continuar = 39;
  public static final int Vacio = 31;
  public static final int Para = 13;
  public static final int LlaveDer = 43;
  public static final int While = 10;
  public static final int Final = 22;
  public static final int Division = 23;
  public static final int Int = 32;
  public static final int Cadena = 19;
  public static final int Publico = 35;
  public static final int For = 12;
  public static final int P_coma = 45;
  public static final int Hacer = 9;
  public static final int EOF = 0;
  public static final int ParDer = 27;
  public static final int error = 1;
  public static final int Romper = 49;
  public static final int Tipo = 2;
  public static final int Op_atribucion = 15;
  public static final int ERROR = 47;
  public static final int Do = 8;
  public static final int SiDefinido = 48;
  public static final int Continue = 36;
  public static final int Op_logico = 21;
  public static final int Public = 34;
  public static final int CorcheteDer = 20;
  public static final int Entonces = 7;
  public static final int Identificador = 46;
  public static final int Si = 5;
  public static final int Resta = 37;
  public static final int Sino = 50;
  public static final int Mientras = 11;
  public static final int Multiplicacion = 40;
  public static final int Op_incremento = 16;
  public static final int FinDefinido = 24;
  public static final int Numero = 53;
  public static final int Suma = 41;
  public static final int Main = 44;
  public static final int Igual = 18;
  public static final int LlaveIzq = 42;
  public static final int Comillas = 3;
}

